name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      env:
        CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload.payload) }}
      run: echo "$CLIENT_PAYLOAD" > metadata.json

    - name: Upload metadata.json
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce #v3.1.2
      with:
        name: metadata.json
        path: metadata.json
