# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      env:
        CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload.payload) }}
      run: echo "$CLIENT_PAYLOAD" > metadata.json

    - name: Upload metadata.json
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: metadata.json
        path: metadata.json
