name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      env:
        CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload.payload) }}
      run: echo "$CLIENT_PAYLOAD" > metadata.json

    - name: Upload metadata.json
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v3.1.3
      with:
        name: metadata.json
        path: metadata.json
