name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      run: echo "${{ github.event.client_payload.payload }}" | tee -a metadata.json

    - name: Upload metadata.json
      uses: actions/upload-artifact@v3
      with:
        name: metadata.json
        path: metadata.json
