# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      env:
        CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload.payload) }}
      run: echo "$CLIENT_PAYLOAD" > metadata.json

    - name: Upload metadata.json
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: metadata.json
        path: metadata.json
