name: persist-metadata
author: Release Engineering <rel-eng@hashicorp.com>
description: Persists metadata used by Common Release Tooling

runs:
  using: composite
  
  steps:
    - name: Write metadata.json
      shell: bash
      # if: repository_dispatch
      run: echo "${{ toJSON(github.event.client_payload.payload) }}" > metadata.json

    - name: Upload metadata.json
      uses: actions/upload-metadata
      with:
        name: metadata.json
        path: metadata.json
